"""
AMRIT AI Code Generation System
Generates code in multiple programming languages based on user requirements
"""

from typing import Dict, List, Optional, Any
from datetime import datetime
import amrit_config as config
from secure_storage import secure_storage


class CodeGenerator:
    """
    Multi-language code generation system for AMRIT AI
    Generates complete projects, functions, and code snippets
    """
    
    def __init__(self):
        self.generation_history = []
        self._load_preferences()
    
    def _load_preferences(self):
        """Load user's coding preferences"""
        self.coding_preferences = secure_storage.load_preference('coding_style') or {
            'preferred_languages': ['Python', 'JavaScript'],
            'code_style': 'clean',
            'comment_style': 'detailed',
            'naming_convention': 'snake_case'
        }
    
    def generate_code(self, 
                     description: str, 
                     language: str = 'Python',
                     project_type: Optional[str] = None) -> Dict[str, Any]:
        """
        Generate code based on description
        
        Args:
            description: Natural language description of what to build
            language: Programming language to use
            project_type: Type of project (Website, Mobile App, etc.)
        
        Returns:
            Generated code and metadata
        """
        if language not in config.SUPPORTED_LANGUAGES:
            return {
                'success': False,
                'error': f'Language {language} not supported yet. Supported: {config.SUPPORTED_LANGUAGES}'
            }
        
        # In real implementation, this would use AI/ML models to generate actual code
        # For now, we create template-based code
        
        code_result = self._generate_template_code(description, language, project_type)
        
        # Save to project storage
        project_data = {
            'description': description,
            'language': language,
            'project_type': project_type,
            'code': code_result['code'],
            'files': code_result.get('files', {}),
            'instructions': code_result.get('instructions', '')
        }
        
        project_id = secure_storage.save_project(description[:50], project_data)
        
        # Update generation history
        self.generation_history.append({
            'project_id': project_id,
            'description': description,
            'language': language,
            'timestamp': datetime.now().isoformat()
        })
        
        # Learn from this generation
        self._learn_from_generation(description, language, project_type)
        
        return {
            'success': True,
            'project_id': project_id,
            'language': language,
            'project_type': project_type,
            'code': code_result['code'],
            'files': code_result.get('files', {}),
            'instructions': code_result.get('instructions', ''),
            'message': f'✅ Code generated successfully in {language}!'
        }
    
    def _generate_template_code(self, description: str, language: str, project_type: Optional[str]) -> Dict[str, Any]:
        """Generate template-based code (placeholder for actual AI generation)"""
        
        templates = {
            'Python': self._generate_python_template,
            'JavaScript': self._generate_javascript_template,
            'Java': self._generate_java_template,
            'C++': self._generate_cpp_template
        }
        
        generator = templates.get(language, self._generate_generic_template)
        return generator(description, project_type)
    
    def _generate_python_template(self, description: str, project_type: Optional[str]) -> Dict[str, Any]:
        """Generate Python code template"""
        
        if project_type == 'Website':
            code = f'''"""
{description}
Generated by AMRIT AI
"""

from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

@app.route('/')
def home():
    """Home page"""
    return render_template('index.html')

@app.route('/api/data', methods=['GET', 'POST'])
def api_data():
    """API endpoint"""
    if request.method == 'POST':
        data = request.json
        # Process data here
        return jsonify({{'success': True, 'data': data}})
    return jsonify({{'message': 'Welcome to {description}'}})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
'''
            files = {
                'app.py': code,
                'requirements.txt': 'flask>=2.0.0\n',
                'templates/index.html': '''<!DOCTYPE html>
<html>
<head>
    <title>Generated by AMRIT AI</title>
</head>
<body>
    <h1>Welcome</h1>
    <p>This website was generated by AMRIT AI</p>
</body>
</html>'''
            }
            
            instructions = '''
To run this application:
1. Install dependencies: pip install -r requirements.txt
2. Run the app: python app.py
3. Open browser: http://localhost:5000
'''
            
        elif project_type == 'API Server':
            code = f'''"""
{description}
Generated by AMRIT AI - REST API Server
"""

from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# In-memory data store (replace with database in production)
data_store = []

@app.route('/api/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({{'status': 'healthy', 'service': '{description}'}})

@app.route('/api/items', methods=['GET', 'POST'])
def handle_items():
    """Handle items CRUD operations"""
    if request.method == 'GET':
        return jsonify({{'items': data_store}})
    
    elif request.method == 'POST':
        item = request.json
        data_store.append(item)
        return jsonify({{'success': True, 'item': item}}), 201

@app.route('/api/items/<int:item_id>', methods=['GET', 'PUT', 'DELETE'])
def handle_item(item_id):
    """Handle single item operations"""
    if item_id >= len(data_store):
        return jsonify({{'error': 'Item not found'}}), 404
    
    if request.method == 'GET':
        return jsonify({{'item': data_store[item_id]}})
    
    elif request.method == 'PUT':
        data_store[item_id] = request.json
        return jsonify({{'success': True, 'item': data_store[item_id]}})
    
    elif request.method == 'DELETE':
        item = data_store.pop(item_id)
        return jsonify({{'success': True, 'deleted': item}})

if __name__ == '__main__':
    print("🚀 API Server starting...")
    print("📡 API available at: http://localhost:8000")
    app.run(debug=True, host='0.0.0.0', port=8000)
'''
            files = {
                'api_server.py': code,
                'requirements.txt': 'flask>=2.0.0\nflask-cors>=3.0.0\n'
            }
            
            instructions = '''
To run this API server:
1. Install dependencies: pip install -r requirements.txt
2. Run the server: python api_server.py
3. Test with: curl http://localhost:8000/api/health
'''
        
        else:
            # Generic Python application
            code = f'''"""
{description}
Generated by AMRIT AI
"""

def main():
    """Main function"""
    print("🔮 AMRIT AI Generated Application")
    print("Description: {description}")
    
    # Your code logic here
    print("Application running successfully!")

if __name__ == '__main__':
    main()
'''
            files = {'main.py': code}
            instructions = 'Run with: python main.py'
        
        return {
            'code': code,
            'files': files,
            'instructions': instructions
        }
    
    def _generate_javascript_template(self, description: str, project_type: Optional[str]) -> Dict[str, Any]:
        """Generate JavaScript code template"""
        
        code = f'''/**
 * {description}
 * Generated by AMRIT AI
 */

// Main application logic
function main() {{
    console.log('🔮 AMRIT AI Generated Application');
    console.log('Description: {description}');
    
    // Your code logic here
    console.log('Application running successfully!');
}}

// Run the application
main();

module.exports = {{ main }};
'''
        
        return {
            'code': code,
            'files': {'index.js': code},
            'instructions': 'Run with: node index.js'
        }
    
    def _generate_java_template(self, description: str, project_type: Optional[str]) -> Dict[str, Any]:
        """Generate Java code template"""
        
        code = f'''/**
 * {description}
 * Generated by AMRIT AI
 */

public class Main {{
    public static void main(String[] args) {{
        System.out.println("🔮 AMRIT AI Generated Application");
        System.out.println("Description: {description}");
        
        // Your code logic here
        System.out.println("Application running successfully!");
    }}
}}
'''
        
        return {
            'code': code,
            'files': {'Main.java': code},
            'instructions': 'Compile with: javac Main.java\\nRun with: java Main'
        }
    
    def _generate_cpp_template(self, description: str, project_type: Optional[str]) -> Dict[str, Any]:
        """Generate C++ code template"""
        
        code = f'''/**
 * {description}
 * Generated by AMRIT AI
 */

#include <iostream>
#include <string>

int main() {{
    std::cout << "🔮 AMRIT AI Generated Application" << std::endl;
    std::cout << "Description: {description}" << std::endl;
    
    // Your code logic here
    std::cout << "Application running successfully!" << std::endl;
    
    return 0;
}}
'''
        
        return {
            'code': code,
            'files': {'main.cpp': code},
            'instructions': 'Compile with: g++ main.cpp -o app\\nRun with: ./app'
        }
    
    def _generate_generic_template(self, description: str, project_type: Optional[str]) -> Dict[str, Any]:
        """Generate generic code template"""
        
        code = f'''// {description}
// Generated by AMRIT AI

// Main application code goes here
'''
        
        return {
            'code': code,
            'files': {'main.txt': code},
            'instructions': 'Template generated. Implement specific logic as needed.'
        }
    
    def _learn_from_generation(self, description: str, language: str, project_type: Optional[str]):
        """Learn from code generation to improve future generations"""
        
        pattern_data = {
            'description': description,
            'language': language,
            'project_type': project_type
        }
        
        secure_storage.save_learned_pattern('code_generation', pattern_data)
        
        # Update coding preferences
        if language not in self.coding_preferences.get('preferred_languages', []):
            self.coding_preferences['preferred_languages'] = self.coding_preferences.get('preferred_languages', []) + [language]
            secure_storage.save_preference('coding_style', self.coding_preferences)
    
    def get_generation_history(self) -> List[Dict[str, Any]]:
        """Get history of code generations"""
        return self.generation_history
    
    def optimize_code(self, code: str, language: str) -> Dict[str, Any]:
        """Optimize existing code"""
        
        # In real implementation, would use AI to optimize code
        # For now, return original with suggestions
        
        return {
            'optimized_code': code,
            'improvements': [
                'Code is already well-structured',
                'Consider adding error handling',
                'Consider adding type hints (Python) or types (TypeScript)'
            ],
            'message': 'Code optimization suggestions provided'
        }


# Global code generator instance
code_generator = CodeGenerator()
